# Author: Roxana Kovaci

variables:
- name: BuildParameters.solution
  value: '**\*.sln'
- name: BuildConfiguration
  value: Release
- name: BuildPlatform
  value: 'Any CPU'

resources:
  repositories:
  - repository: InvisibilityCloak
    type: github
    endpoint: rkovaci92
    name: xforcered/InvisibilityCloak
  - repository: Farmer 
    type: github
    endpoint: rkovaci92
    name: mdsecactivebreach/Farmer
  - repository: Rubeus
    type: github
    endpoint: rkovaci92
    name: GhostPack/Rubeus
  - repository: Seatbelt 
    type: github
    endpoint: rkovaci92
    name: GhostPack/Seatbelt
  - repository: SafetyKatz 
    type: github
    endpoint: rkovaci92
    name: GhostPack/SafetyKatz
  - repository: SharpUp
    type: github
    endpoint: rkovaci92
    name: GhostPack/SharpUp
  - repository: SharpDPAPI 
    type: github
    endpoint: rkovaci92
    name: GhostPack/SharpDPAPI
  - repository: Certify 
    type: github
    endpoint: rkovaci92
    name: GhostPack/Certify
  - repository: KrbRelayUp
    type: github
    endpoint: rkovaci92
    name: Dec0ne/KrbRelayUp
  - repository: Snaffler 
    type: github
    endpoint: rkovaci92
    name: SnaffCon/Snaffler
  - repository: SharpSQL 
    type: github
    endpoint: rkovaci92
    name: mlcsec/SharpSQL
  - repository: SharpWebServer
    type: github
    endpoint: rkovaci92
    name: mgeeky/SharpWebServer
  - repository: SharpWMI 
    type: github
    endpoint: rkovaci92
    name: GhostPack/SharpWMI
  - repository: SharpMiniDump
    type: github
    endpoint: rkovaci92
    name: b4rtik/SharpMiniDump
  - repository: Internal-Monologue 
    type: github
    endpoint: rkovaci92
    name: eladshamir/Internal-Monologue
  - repository: Whisker 
    type: github
    endpoint: rkovaci92
    name: eladshamir/Whisker
  - repository: StandIn
    type: github
    endpoint: rkovaci92
    name: FuzzySecurity/StandIn
  - repository: SharpView 
    type: github
    endpoint: rkovaci92
    name: tevora-threat/SharpView
  - repository: SharpHound 
    type: github
    endpoint: rkovaci92
    name: BloodHoundAD/SharpHound3
  - repository: KrbRelay
    type: github
    endpoint: rkovaci92
    name: cube0x0/KrbRelay
  - repository: MalSCCM
    type: github
    endpoint: rkovaci92
    name: nettitude/MalSCCM
  - repository: SharpWSUS
    type: github
    endpoint: rkovaci92
    name: nettitude/SharpWSUS
  - repository: Group3r
    type: github
    endpoint: rkovaci92
    name: Group3r/Group3r
  - repository: netsh_acl_enumerator
    type: github
    endpoint: rkovaci92
    name: leftp/netsh_acl_enumerator
  - repository: noPac
    type: github
    endpoint: rkovaci92
    name: cube0x0/noPac
  - repository: SharpLAPS
    type: github
    endpoint: rkovaci92
    name: swisskyrepo/SharpLAPS
  - repository: SharpSystemTriggers
    type: github
    endpoint: rkovaci92
    name: cube0x0/SharpSystemTriggers
  - repository: RequestAADRefreshToken
    type: github
    endpoint: rkovaci92
    name: leechristensen/RequestAADRefreshToken
  - repository: ROADtoken
    type: github
    endpoint: rkovaci92
    name: dirkjanm/ROADtoken
  - repository: LiquidSnake
    type: github
    endpoint: rkovaci92
    name: RiccardoAncarani/LiquidSnake
  - repository: SearchOutlook
    type: github
    endpoint: rkovaci92
    name: RedLectroid/SearchOutlook
  - repository: SharpChisel
    type: github
    endpoint: rkovaci92
    name: shantanu561993/SharpChisel


trigger:
- main

pool:
  vmImage: 'windows-2019'

steps:
- checkout: Farmer
- checkout: Rubeus
- checkout: Seatbelt
- checkout: SafetyKatz
- checkout: SharpUp
- checkout: SharpDPAPI
- checkout: Certify
- checkout: KrbRelayUp
- checkout: KrbRelay
- checkout: Snaffler
- checkout: SharpSQL
- checkout: SharpWebServer
- checkout: SharpWMI
- checkout: SharpMiniDump
- checkout: Internal-Monologue
- checkout: Whisker
- checkout: StandIn
- checkout: SharpView
- checkout: SharpHound
- checkout: MalSCCM
- checkout: SharpWSUS
- checkout: Group3r
- checkout: netsh_acl_enumerator
- checkout: noPac
- checkout: SharpLAPS
- checkout: SharpSystemTriggers
- checkout: ROADtoken
- checkout: RequestAADRefreshToken
- checkout: LiquidSnake
- checkout: SearchOutlook
- checkout: SharpChisel
- checkout: InvisibilityCloak

- task: NuGetToolInstaller@0
  displayName: Use NuGet 4.4.1
  inputs:
    versionSpec: 4.4.1
- task: NuGetCommand@2
  displayName: NuGet restore
  inputs:
    solution: $(BuildParameters.solution)
  
- task: PowerShell@2
  displayName: PowerShell Script for StandIn
  inputs:
    targetType: inline
    script: "Set-Content D:\\a\\1\\s\\StandIn\\StandIn\\FodyWeavers.xml '<?xml version=\"1.0\" encoding=\"utf-8\" ?>'\nAdd-Content D:\\a\\1\\s\\StandIn\\StandIn\\FodyWeavers.xml '<Weavers>'\nAdd-Content D:\\a\\1\\s\\StandIn\\StandIn\\FodyWeavers.xml '<Costura>'\nAdd-Content D:\\a\\1\\s\\StandIn\\StandIn\\FodyWeavers.xml 'DisableCleanup=\"true\"'\nAdd-Content D:\\a\\1\\s\\StandIn\\StandIn\\FodyWeavers.xml '<IncludeAssemblies>'\nAdd-Content D:\\a\\1\\s\\StandIn\\StandIn\\FodyWeavers.xml 'CommandLine'\nAdd-Content D:\\a\\1\\s\\StandIn\\StandIn\\FodyWeavers.xml '</IncludeAssemblies>'\nAdd-Content D:\\a\\1\\s\\StandIn\\StandIn\\FodyWeavers.xml '</Costura>'\nAdd-Content D:\\a\\1\\s\\StandIn\\StandIn\\FodyWeavers.xml '</Weavers>'"
  
- task: PowerShell@2
  displayName: PowerShell Script for SharpView
  inputs:
    targetType: inline
    script: "Set-Content D:\\a\\1\\s\\SharpView\\FodyWeavers.xml '<?xml version=\"1.0\" encoding=\"utf-8\" ?>'\nAdd-Content D:\\a\\1\\s\\SharpView\\FodyWeavers.xml '<Weavers>'\nAdd-Content D:\\a\\1\\s\\SharpView\\FodyWeavers.xml '<Costura>'\nAdd-Content D:\\a\\1\\s\\SharpView\\FodyWeavers.xml 'DisableCleanup=\"true\"'\nAdd-Content D:\\a\\1\\s\\SharpView\\FodyWeavers.xml '<IncludeAssemblies>'\nAdd-Content D:\\a\\1\\s\\SharpView\\FodyWeavers.xml 'CommandLine'\nAdd-Content D:\\a\\1\\s\\SharpView\\FodyWeavers.xml '</IncludeAssemblies>'\nAdd-Content D:\\a\\1\\s\\SharpView\\FodyWeavers.xml '</Costura>'\nAdd-Content D:\\a\\1\\s\\SharpView\\FodyWeavers.xml '</Weavers>'"

- task: PowerShell@2
  displayName: PowerShell Script for SharpHound
  inputs:
    targetType: inline
    script: "Set-Content D:\\a\\1\\s\\SharpHound3\\FodyWeavers.xml '<?xml version=\"1.0\" encoding=\"utf-8\" ?>'\nAdd-Content D:\\a\\1\\s\\SharpHound3\\FodyWeavers.xml '<Weavers>'\nAdd-Content D:\\a\\1\\s\\SharpHound3\\FodyWeavers.xml '<Costura>'\nAdd-Content D:\\a\\1\\s\\SharpHound3\\FodyWeavers.xml 'DisableCleanup=\"true\"'\nAdd-Content D:\\a\\1\\s\\SharpHound3\\FodyWeavers.xml '<IncludeAssemblies>'\nAdd-Content D:\\a\\1\\s\\SharpHound3\\FodyWeavers.xml 'CommandLine'\nAdd-Content D:\\a\\1\\s\\SharpHound3\\FodyWeavers.xml '</IncludeAssemblies>'\nAdd-Content D:\\a\\1\\s\\SharpHound3\\FodyWeavers.xml '</Costura>'\nAdd-Content D:\\a\\1\\s\\SharpHound3\\FodyWeavers.xml '</Weavers>'"
  
- task: VSBuild@1
  displayName: Build solution **\*.sln
  inputs:
    solution: $(BuildParameters.solution)
    platform: $(BuildPlatform)
    configuration: $(BuildConfiguration)
- task: VSTest@2
  displayName: VsTest - testAssemblies
  inputs:
    testAssemblyVer2: >-
      **\$(BuildConfiguration)\*test*.dll
       !**\obj\**
    platform: $(BuildPlatform)
    configuration: $(BuildConfiguration)
- task: PublishSymbols@2
  displayName: Publish symbols path
  continueOnError: True
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
    SymbolServerType: TeamServices
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
  inputs:
    SourceFolder: $(system.defaultworkingdirectory)
    Contents: '**\bin\$(BuildConfiguration)\**'
    TargetFolder: $(build.artifactstagingdirectory)

- task: CopyFiles@2
  displayName: 'Copy Dependencies to: $(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
  inputs:
    SourceFolder: $(system.defaultworkingdirectory)\StandIn\StandIn\packages\
    Contents: '**'
    TargetFolder: $(build.artifactstagingdirectory)\StandIn\StandIn\StandIn\bin\Release\

- task: CopyFiles@2
  displayName: 'Copy Dependencies to: $(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
  inputs:
    SourceFolder: $(system.defaultworkingdirectory)\SharpView\
    Contents: '**'
    TargetFolder: $(build.artifactstagingdirectory)\SharpView\SharpView\bin\Release\
- task: CopyFiles@2
  displayName: 'Copy Dependencies to: $(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
  inputs:
    SourceFolder: $(system.defaultworkingdirectory)\SharpHound3\packages\
    Contents: '**'
    TargetFolder: $(build.artifactstagingdirectory)\SharpHound3\bin\Release\

- task: PowerShell@2
  displayName: PowerShell Script for ConfuserEx
  inputs:
    targetType: inline
    script: |
      # make the confused folder
      mkdir D:\a\1\a\Confused\

      # download specific ConfuserEx version
      wget https://github.com/mkaring/ConfuserEx/releases/download/v1.6.0/ConfuserEx-CLI.zip -o ConfuserEx-CLI.zip
      Expand-Archive .\ConfuserEx-CLI.zip

      # copy dependencies
      cp D:\a\1\a\StandIn\StandIn\StandIn\bin\Release\CommandLineParser.1.9.3.15\lib\CommandLine.dll D:\a\1\a\StandIn\StandIn\StandIn\bin\Release\CommandLine.dll
      cp D:\a\1\a\SharpView\SharpView\bin\Release\packages\PCRE.NET.0.7.0\lib\net45\PCRE.NET.dll D:\a\1\a\SharpView\SharpView\bin\Release\PCRE.NET.dll
      cp D:\a\1\a\SharpHound3\bin\Release\CommandLineParser.2.7.82\lib\net40\CommandLine.dll D:\a\1\a\SharpHound3\SharpHound3\bin\Release\CommandLine.dll
      cp D:\a\1\a\SharpHound3\bin\Release\DnsClient.1.2.0\lib\net45\DnsClient.dll D:\a\1\a\SharpHound3\SharpHound3\bin\Release\DnsClient.dll
      cp D:\a\1\a\SharpHound3\bin\Release\SharpZipLib.1.2.0\lib\net45\ICSharpCode.SharpZipLib.dll D:\a\1\a\SharpHound3\SharpHound3\bin\Release\ICSharpCode.SharpZipLib.dll
      cp D:\a\1\a\SharpHound3\bin\Release\System.Threading.Tasks.Dataflow.4.11.0\lib\portable-net45+win8+wpa81\System.Threading.Tasks.Dataflow.dll D:\a\1\a\SharpHound3\SharpHound3\bin\Release\System.Threading.Tasks.Dataflow.dll
      
      # create confuser crpoj file
      New-Item D:\a\1\a\conf.crproj
      Set-Content D:\a\1\a\conf.crproj '<?xml version="1.0" encoding="utf-8"?>'
      Add-Content D:\a\1\a\conf.crproj '<project outputDir="D:\a\1\a\Confused\" baseDir="D:\a\1\a\" xmlns="http://confuser.codeplex.com">'
      Add-Content D:\a\1\a\conf.crproj '<rule preset="maximum" pattern="true">'
      Add-Content D:\a\1\a\conf.crproj '<protection id="anti debug" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="anti dump" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="anti ildasm" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="anti tamper" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="constants" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="ctrl flow" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="harden" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="invalid metadata" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="ref proxy" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="rename" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="resources" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="typescramble" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="watermark" action="remove" />'
      Add-Content D:\a\1\a\conf.crproj '</rule>'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\Rubeus\Rubeus\bin\Release\Rubeus.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\Seatbelt\Seatbelt\bin\Release\Seatbelt.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\Farmer\Farmer\bin\Release\Farmer.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\SafetyKatz\SafetyKatz\bin\Release\SafetyKatz.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\SharpUp\SharpUp\bin\Release\SharpUp.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\SharpDPAPI\SharpDPAPI\bin\Release\SharpDPAPI.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\SharpDPAPI\SharpChrome\bin\Release\SharpChrome.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\Certify\Certify\bin\Release\Certify.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\KrbRelayUp\KrbRelayUp\bin\Release\KrbRelayUp.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\Snaffler\Snaffler\bin\Release\Snaffler.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\SharpSQL\SharpSQL\bin\Release\net4.0\SharpSQL.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\SharpWebServer\SharpWebServer\bin\Release\SharpWebServer.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\SharpMiniDump\SharpMiniDump\bin\Release\SharpMiniDump.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\SharpWMI\SharpWMI\bin\Release\SharpWMI.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\Internal-Monologue\InternalMonologueEXE\bin\Release\InternalMonologue.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\Whisker\Whisker\bin\Release\Whisker.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\StandIn\StandIn\StandIn\bin\Release\StandIn.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\SharpView\SharpView\bin\Release\SharpView.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\SharpHound3\SharpHound3\bin\Release\SharpHound.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\SharpWSUS\SharpWSUS\bin\Release\SharpWSUS.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\SharpLAPS\SharpLAPS\bin\Release\SharpLAPS.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\noPac\noPac\bin\Release\noPac.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\netsh_acl_enumerator\netsh_enumerator\bin\Release\netsh_enumerator.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\MalSCCM\MalSCCM\bin\Release\MalSCCM.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\KrbRelay\KrbRelay\bin\Release\KrbRelay.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\KrbRelay\CheckPort\bin\Release\CheckPort.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\Group3r\Group3r\bin\Release\Group3r.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\SharpSystemTriggers\Midl2Bytes\bin\Release\Midl2Bytes.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\SharpSystemTriggers\SharpDcomTrigger\bin\Release\SharpDcomTrigger.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\SharpSystemTriggers\SharpEfsTrigger\bin\Release\SharpEfsTrigger.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\SharpSystemTriggers\SharpSpoolTrigger\bin\Release\SharpSpoolTrigger.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\ROADtoken\bin\Release\ROADtoken.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\RequestAADRefreshToken\RequestAADRefreshToken\bin\Release\RequestAADRefreshToken.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\LiquidSnake\CSharpNamedPipeLoader\CSharpNamedPipeLoader\bin\Release\CSharpNamedPipeLoader.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\LiquidSnake\LiquidSnake\LiquidSnake\bin\Release\LiquidSnake.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\SearchOutlook\SearchOutlook\bin\Release\SearchOutlook.exe" />'
      Add-Content D:\a\1\a\conf.crproj '<module path="D:\a\1\a\SharpChisel\SharpChisel\bin\Release\SharpChisel.exe" />'
      Add-Content D:\a\1\a\conf.crproj '</project>'
 

      # execute confuser on everything
      .\ConfuserEx-CLI\Confuser.CLI.exe D:\a\1\a\conf.crproj -n
- task: PowerShell@2
  displayName: PowerShell Script for Confused EXEs
  inputs:
    targetType: inline
    script: |
      mkdir $(Pipeline.Workspace)\a\Output\
      gci -recurse *.exe -Path $(Pipeline.Workspace)\a\Confused\| Move-Item -Destination $(Pipeline.Workspace)\a\Output\
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)\Output\
    TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'

schedules:
- cron: "0 2 * * Mon,Tue,Wed,Thur,Fri"
  displayName: Daily night build
  branches:
    include:
    - master
  always: true