# Author: Roxana Kovaci
# Twitter: @RoxanaKovaci

variables:
- name: BuildParameters.solution
  value: '**\*.sln'
- name: BuildConfiguration
  value: Release
- name: BuildPlatform
  value: 'Any CPU'

resources:
  repositories:
  - repository: Certify 
    type: github
    endpoint: 2keebs
    name: GhostPack/Certify

pool:
   name: Default
   demands: 
   - Agent.Name -equals KEEBS
# vmImage: 'windows-2019'

steps:
- checkout: Certify

- task: NuGetToolInstaller@0
  displayName: Use NuGet 4.4.1
  inputs:
    versionSpec: 4.4.1
- task: NuGetCommand@2
  displayName: NuGet restore
  inputs:
    solution: $(BuildParameters.solution)

- task: UsePythonVersion@0
  displayName: 'Use Python 3.x'
- task: PowerShell@2
  displayName: PowerShell Script for InvisibilityCloak
  inputs:
    targetType: inline
    script: |
      wget https://raw.githubusercontent.com/xforcered/InvisibilityCloak/main/InvisibilityCloak.py -o InvisibilityCloak.py
      wget https://raw.githubusercontent.com/RoxanaKovaci/Azure-pipelines/master/random-words.py -o words.py

      pip3 install requests
      pip3 install random

      $folders = Get-ChildItem -Path ".\" -directory
      foreach ($f in $folders) {$pos = $(python.exe .\words.py); python.exe .\InvisibilityCloak.py -d $f.FullName -n $pos -m reverse; echo "$f is now $pos" >> .\correlation.txt}

      gc .\correlation.txt

- task: PowerShell@2
  displayName: PowerShell Script for SharpView
  inputs:
    targetType: inline
    script: |
      Set-Content D:\a\1\s\SharpView\FodyWeavers.xml '<?xml version="1.0" encoding="utf-8" ?>'
      Add-Content D:\a\1\s\SharpView\FodyWeavers.xml '<Weavers>'
      Add-Content D:\a\1\s\SharpView\FodyWeavers.xml '<Costura>'
      Add-Content D:\a\1\s\SharpView\FodyWeavers.xml 'DisableCleanup="true"'
      Add-Content D:\a\1\s\SharpView\FodyWeavers.xml '<IncludeAssemblies>'
      Add-Content D:\a\1\s\SharpView\FodyWeavers.xml 'CommandLine'
      Add-Content D:\a\1\s\SharpView\FodyWeavers.xml '</IncludeAssemblies>'
      Add-Content D:\a\1\s\SharpView\FodyWeavers.xml '</Costura>'
      Add-Content D:\a\1\s\SharpView\FodyWeavers.xml '</Weavers>'
- task: PowerShell@2
  displayName: PowerShell Script for SharpHound
  inputs:
    targetType: inline
    script: |
      Set-Content D:\a\1\s\SharpHound\FodyWeavers.xml '<?xml version="1.0" encoding="utf-8" ?>'
      Add-Content D:\a\1\s\SharpHound\FodyWeavers.xml '<Weavers>'
      Add-Content D:\a\1\s\SharpHound\FodyWeavers.xml '<Costura>'
      Add-Content D:\a\1\s\SharpHound\FodyWeavers.xml 'DisableCleanup="true"'
      Add-Content D:\a\1\s\SharpHound\FodyWeavers.xml '<IncludeAssemblies>'
      Add-Content D:\a\1\s\SharpHound\FodyWeavers.xml 'CommandLine'
      Add-Content D:\a\1\s\SharpHound\FodyWeavers.xml '</IncludeAssemblies>'
      Add-Content D:\a\1\s\SharpHound\FodyWeavers.xml '</Costura>'
      Add-Content D:\a\1\s\SharpHound\FodyWeavers.xml '</Weavers>'

- task: VSBuild@1
  displayName: Build solution **\*.sln
  inputs:
    solution: $(BuildParameters.solution)
    platform: $(BuildPlatform)
    configuration: $(BuildConfiguration)
- task: VSTest@2
  displayName: VsTest - testAssemblies
  inputs:
    testAssemblyVer2: >-
      **\$(BuildConfiguration)\*test*.dll
       !**\obj\**
    platform: $(BuildPlatform)
    configuration: $(BuildConfiguration)
- task: PublishSymbols@2
  displayName: Publish symbols path
  continueOnError: True
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
    SymbolServerType: TeamServices
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
  inputs:
    SourceFolder: $(system.defaultworkingdirectory)
    Contents: '**\bin\$(BuildConfiguration)\**'
    TargetFolder: $(build.artifactstagingdirectory)
- task: PowerShell@2
  displayName: PowerShell Script for ConfuserEx
  inputs:
    targetType: inline
    script: |
      # make the confused folder
      mkdir D:\a\1\a\Confused\

      # download specific ConfuserEx version
      wget https://github.com/mkaring/ConfuserEx/releases/download/v1.6.0/ConfuserEx-CLI.zip -o ConfuserEx-CLI.zip
      Expand-Archive .\ConfuserEx-CLI.zip

      # copy dependencies
      $st = "D:\a\1\a\StandIn\*\bin\Release\*.exe"
      $stf = (ls $st).Name
      $sty = ($stf -split ".exe")[0]
      cp D:\a\1\s\StandIn\packages\CommandLineParser.1.9.3.15\lib\CommandLine.dll D:\a\1\a\StandIn\$sty\bin\Release\CommandLine.dll

      $sv = "D:\a\1\a\SharpView\*\bin\Release\*.exe"
      $svf = (ls $sv).Name
      $svy = ($svf -split ".exe")[0]
      cp D:\a\1\s\SharpView\packages\PCRE.NET.0.7.0\lib\net45\PCRE.NET.dll D:\a\1\a\SharpView\$svy\bin\Release\PCRE.NET.dll

      # renamed binaries
      $cf = "D:\a\1\a\Certify\*\bin\Release\*.exe"
      $cff = (ls $cf).Name
      $cfy = ($cff -split ".exe")[0]


      # create confuser crpoj file
      New-Item D:\a\1\a\conf.crproj
      Set-Content D:\a\1\a\conf.crproj '<?xml version="1.0" encoding="utf-8"?>'
      Add-Content D:\a\1\a\conf.crproj '<project outputDir="D:\a\1\a\Confused\" baseDir="D:\a\1\a\" xmlns="http://confuser.codeplex.com">'
      Add-Content D:\a\1\a\conf.crproj '<rule preset="maximum" pattern="true">'
      Add-Content D:\a\1\a\conf.crproj '<protection id="anti debug" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="anti dump" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="anti ildasm" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="anti tamper" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="constants" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="ctrl flow" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="harden" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="invalid metadata" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="ref proxy" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="rename" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="resources" />'
      Add-Content D:\a\1\a\conf.crproj '<protection id="watermark" action="remove" />'
      Add-Content D:\a\1\a\conf.crproj '</rule>'
      Add-Content D:\a\1\a\conf.crproj "<module path='D:\a\1\a\Certify\$cfy\bin\Release\$cff' />" 
      Add-Content D:\a\1\a\conf.crproj "</project>"

      # execute confuser on everything
      .\ConfuserEx-CLI\Confuser.CLI.exe D:\a\1\a\conf.crproj -n
      cp D:\a\1\s\correlation.txt D:\a\1\a\Confused\correlation.txt
      
- task: PowerShell@2
  displayName: PowerShell Script for Confused EXEs
  inputs:
    targetType: inline
    script: |
      mkdir $(Pipeline.Workspace)\a\Output\
      gci -recurse *.exe -Path $(Pipeline.Workspace)\a\Confused\| Move-Item -Destination $(Pipeline.Workspace)\a\Output\
      gci -recurse *.txt -Path $(Pipeline.Workspace)\a\Confused\| Move-Item -Destination $(Pipeline.Workspace)\a\Output\
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)\Output\
    TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'

schedules:
- cron: "0 2 * * Mon,Tue,Wed,Thur,Fri"
  displayName: Daily night builds
  branches:
    include:
    - master
  always: true